### ISSUE TITLE
Add support for configurable number of OTP code digits

### ISSUE THREAD

**Issue by sindilevich** [aerogear/aerogear-windows-otp#1]
*aerogear-windows-otp* should support generating OTP codes with 6-8 digits. Right now, it is hard-coded to generate 6-digits OTP codes only.

**Comment by matzew** [comment]
Feel free to send a PR :)

**Comment by matzew** [comment]
@sindilevich btw. mind to create a JIRA ticket ? We (AeroGear) do not really use GH issues

**Comment by sindilevich** [comment]
@matzew, I would happily do create a JIRA ticket. But, it seems, I have no permission to do so. I've logged in into https://issues.jboss.org/projects/AGWIN, but could not find a *Create a new ticket* button/link.

**Comment by sindilevich** [comment]
@matzew, here is the JIRA ticket: https://issues.jboss.org/browse/AGWIN-12.

**Comment by matzew** [comment]
yay!

@sindilevich thanks!

**Comment by sindilevich** [comment]
Pull request: aerogear/aerogear-windows-otp#2. Also added a link to the PR to the JIRA ticket.
